version: '{branch}.{build}'
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: false
platform: x64
image: 
   - Ubuntu
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
init:
  - cmd: git config --global core.autocrlf true
install:
  - echo "install"
build_script:
  - echo "build"
after_build:
  - echo "after"
on_finish:
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
