version: '{branch}.{build}'
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: false
platform: x64
image: 
   - Ubuntu
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
init:
  - cmd: git config --global core.autocrlf true
install:
  - sudo apt clean
  - sudo apt update
  - sudo apt -y install blobfuse fuse
  - sudo apt -y install imagemagick
  - sudo apt -y install rename
  - sudo apt -y install webp
build_script:
  - sudo mkdir /mnt/blobfusetmp
  - sudo chown appveyor /mnt/blobfusetmp
  - sudo mount -t tmpfs -o size=16g tmpfs /mnt/blobfusetmp
  - sudo mkdir /mnt/blob
  - sudo chown appveyor /mnt/blob
  - blobfuse /mnt/blob --tmp-path=/mnt/blobfusetmp -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120 --file-cache-timeout-in-seconds=120 --container-name=$AZURE_STORAGE_CONTAINER
  - AZURE_STORAGE_MOUNT=/mnt/blob python3 ./processTasks.py
after_build:
  - echo "after"
on_finish:
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
